export default defineNuxtConfig({
  buildDir: process.env.NUXT_BUILD_DIR || ".nuxt",
  compatibilityDate: "2026-10-08",
  devtools: { enabled: false },
  ssr: false,
  icon: {
    provider: "none",
    fallbackToApi: false,
    clientBundle: {
      scan: true,
      icons: [
        "lucide:arrow-right",
        "lucide:calendar-days",
        "lucide:check",
        "lucide:check-check",
        "lucide:chevron-down",
        "lucide:chevron-left",
        "lucide:chevron-right",
        "lucide:chevron-up",
        "lucide:circle-check",
        "lucide:clock-3",
        "lucide:columns-2",
        "lucide:copy",
        "lucide:download",
        "lucide:layout-dashboard",
        "lucide:list",
        "lucide:list-checks",
        "lucide:list-todo",
        "lucide:loader-circle",
        "lucide:lock-keyhole",
        "lucide:log-out",
        "lucide:menu",
        "lucide:pencil",
        "lucide:plus",
        "lucide:search",
        "lucide:settings",
        "lucide:sprout",
        "lucide:sun",
        "lucide:trash-2",
        "lucide:x",
      ],
    },
  },
  modules: ["@nuxt/ui"],
  css: ["~/assets/css/main.css"],
  typescript: { strict: true },
  runtimeConfig: { public: { apiBaseUrl: "http://127.0.0.1:8012/api" } },
  fonts: {
    providers: {
      google: false,
      bunny: false,
      fontshare: false,
      fontsource: false,
      adobe: false,
    },
  },
  colorMode: { preference: "light" },
  app: {
    head: {
      title: "Mes listes de tâches",
      htmlAttrs: { lang: "fr" },
      link: [{ rel: "icon", type: "image/svg+xml", href: "/favicon.svg" }],
      meta: [
        {
          name: "description",
          content:
            "Organisez vos tâches privées par liste, priorité et échéance.",
        },
      ],
    },
  },
});
